name: ReleaseCI
on:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Release documents to AWS S3
    run: bash scripts/pipeline/release.sh ${{secrets.AWS_Bucket_Name}} "folder/myapp.zip" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "myapp.zip"