name: ReleaseCI
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "scripts/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Diffs
        id: changed-files
        run: echo "changed_files=$(git diff --name-only ${{github.event.before}} ${{github.event.after}})" >> $GITHUB_ENV

      - name: List changed files and Upload in AWS S3
        env:
          CHANGED_FILES: ${{steps.changed-files.outputs.changed_files}}
        run: |
          echo $CHANGED_FILES;
          for file in $CHANGED_FILES; do
            if [ "$file" != ".github/workflows/release.yml" ] || [ "$file" != "scripts/pipeline/release.sh" ] || [ "$file" != "scripts/pipeline/upload_file_to_s3.py" ]; then
            echo "$file was changeddd"
          done

      # - name: Release documents to AWS S3
      #   run: bash scripts/pipeline/release.sh ${{secrets.AWS_Bucket_Name}} "app/myapp.zip" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "myapp.zip"
